[env]
MINECRAFT_VERSION = "{{ get_env(name='MINECRAFT_VERSION', default='1.21.8') }}"
MINECRAFT_EULA = "{{ get_env(name='MINECRAFT_EULA', default='false') }}"
MINECRAFT_DIR = "{{ get_env(name='MINECRAFT_DIR', default='/minecraft') }}"

MINECRAFT_SERVER_PROPERTIES_DIFFICULTY = "{{ get_env(name='MINECRAFT_SERVER_PROPERTIES_DIFFICULTY', default='easy') }}"
MINECRAFT_SERVER_PROPERTIES_SERVER_PORT = "{{ get_env(name='MINECRAFT_SERVER_PROPERTIES_SERVER_PORT', default='4040') }}"

[tools]
java = "21"
cargo-binstall = "latest"
