[env]
MINECRAFT_VERSION = "{{ get_env(name='MINECRAFT_VERSION', default='1.21.8') }}"
MINECRAFT_EULA = "{{ get_env(name='MINECRAFT_EULA', default='false') }}"
MINECRAFT_DIR = "{{ get_env(name='MINECRAFT_DIR', default='/minecraft') }}"

MINECRAFT_SERVER_PROPERTIES_DIFFICULTY = "{{ get_env(name='MINECRAFT_SERVER_PROPERTIES_DIFFICULTY', default='easy') }}"
MINECRAFT_SERVER_PROPERTIES_GAMEMODE = "{{ get_env(name='MINECRAFT_SERVER_PROPERTIES_GAMEMODE', default='survival') }}"
MINECRAFT_SERVER_PROPERTIES_LEVEL_SEED = "{{ get_env(name='MINECRAFT_SERVER_PROPERTIES_LEVEL_SEED', default='') }}"
MINECRAFT_SERVER_PROPERTIES_MAX_PLAYERS = "{{ get_env(name='MINECRAFT_SERVER_PROPERTIES_MAX_PLAYERS', default='20') }}"
MINECRAFT_SERVER_PROPERTIES_MOTD = "{{ get_env(name='MINECRAFT_SERVER_PROPERTIES_MOTD', default='A Minecraft Server') }}"
MINECRAFT_SERVER_PROPERTIES_ONLINE_MODE = "{{ get_env(name='MINECRAFT_SERVER_PROPERTIES_ONLINE_MODE', default='true') }}"
MINECRAFT_SERVER_PROPERTIES_SERVER_PORT = "{{ get_env(name='MINECRAFT_SERVER_PROPERTIES_SERVER_PORT', default='4040') }}"
MINECRAFT_SERVER_PROPERTIES_SIMULATION_DISTANCE = "{{ get_env(name='MINECRAFT_SERVER_PROPERTIES_SIMULATION_DISTANCE', default='10') }}"
MINECRAFT_SERVER_PROPERTIES_SPAWN_PROTECTION = "{{ get_env(name='MINECRAFT_SERVER_PROPERTIES_SPAWN_PROTECTION', default='16') }}"
MINECRAFT_SERVER_PROPERTIES_VIEW_DISTANCE = "{{ get_env(name='MINECRAFT_SERVER_PROPERTIES_VIEW_DISTANCE', default='10') }}"

[tools]
java = "21"
cargo-binstall = "latest"
